name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Helm Lint
        run: |
          cd charts/nginx-app
          helm lint .

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-terraform
          aws-region: us-east-1

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem

      - name: Wait for EC2
        run: sleep 60

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'

            if [ ! -d "k8s-deployment-automation" ]; then
              git clone https://github.com/bmfranco/k8s-deployment-automation.git
            else
              cd k8s-deployment-automation && git pull && cd ..
            fi

            cd k8s-deployment-automation/charts/nginx-app

            helm upgrade --install nginx . \
              --set message="Hello World - Deploy via CI/CD - Commit $GITHUB_SHA"

          EOF