name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Helm Lint
        run: |
          cd charts/nginx-app
          helm lint .

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-terraform
          aws-region: us-east-1

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem

      - name: Wait for EC2 (retry SSH)
        run: |
          for i in {1..10}; do
            echo "Tentativa $i de conexão SSH..."
            ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i ~/.ssh/key.pem ec2-user@${{ secrets.EC2_HOST }} "echo conectado" && break
            sleep 15
          done

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/key.pem ec2-user@${{ secrets.EC2_HOST }} << EOF

            echo "Aguardando cloud-init finalizar..."
            while [ ! -f /var/lib/cloud/instance/boot-finished ]; do
              sleep 5
            done

            # garantir git
            if ! command -v git &> /dev/null; then
              sudo yum install -y git
            fi

            # aguardar Kubernetes
            echo "Aguardando Kubernetes..."
            until kubectl get nodes &> /dev/null; do
              sleep 10
            done

            # clonar ou atualizar repo
            if [ ! -d "k8s-deployment-automation" ]; then
              git clone https://github.com/bmfranco/k8s-deployment-automation.git
            else
              cd k8s-deployment-automation && git pull && cd ..
            fi

            cd k8s-deployment-automation/charts/nginx-app

            helm upgrade --install nginx . \
              --set message="Hello World - Deploy via CI/CD - Commit $GITHUB_SHA"

          EOF